### ISSUE TITLE
An error occured while initiating transaction Error: Hashes do not match!

### ISSUE THREAD

**Issue by fraud47** [paynow/Paynow-NodeJS-SDK#26]
mobile payement not working

An error occured while initiating transaction Error: Hashes do not match!
    at Paynow.parse (C:\Users\USER\Documents\projects\nodejs\league\leaguebackend\node_modules\paynow\dist\paynow.js:101:23)
    at C:\Users\USER\Documents\projects\nodejs\league\leaguebackend\node_modules\paynow\dist\paynow.js:87:26
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by venom-napsta** [comment]
feels like they just dont want to fix this issue

**Comment by iammerus** [comment]
@TafadzwaD @venom-napsta @fraud47 As far as I know, the SDK is throwing an erroneous `Hash Mismatch` when you try using keys that are not live to initiate a mobile transaction. 

Though the SDK should better handle and give a better message when that's the case, a quick fix is just ensuring you're using live credentials when you're using your own numbers for testing mobile transactions. If your key is still in test mode, use the test numbers as outlined in the [documentation](https://developers.paynow.co.zw/docs/test_mode.html#express-checkout-mobile-money).

I've been a bit tied, and can't find the time to make a PR to give a better message right now. But will try to make sure it happens soon! OSS can be hard.

**Comment by venom-napsta** [comment]
Thanks so much for the effort man. i thought i might be doing this test
wrongs, so please can you just record screen shots doing it. thank you

**Comment by venom-napsta** [comment]
Thanks so much for the effort man. I thought i might be doing this test
wrongly, so please can you just record screen shots doing it, till the
account is left to be set live only, or give us postman/insomnia working
parameters. thank you

**Comment by TafadzwaD** [comment]
@iammerus You efforts are highly appreciated man.. All along I thought that the Paynow Team was behind this package. Anyway we could help??

**Comment by iammerus** [comment]
@venom-napsta Try reading up on how to test mobile transactions with keys that aren't live. There's special numbers you can use to test your integration. Each number gives you a different status update which allows you to test those different scenarios until your app is live.

https://developers.paynow.co.zw/docs/test_mode.html#express-checkout-mobile-money

**Comment by iammerus** [comment]
@TafadzwaD Are you familiar with the SDK's codebase? Or we can have a quick call and I can show you what needs to be updated. Then you can submit a PR to the repo when done. That would save me from having to implement the solution myself

**Comment by user3470** [comment]
Wasted lots and lots of hours on this issue. Whyyyy paynow, why aren't you looking into this?

All you have to do is pass this error message to the user
```status=Error&error=The+integration+ID+specified+is+currently+in+test+mode.+The+authemail+used+must+belong+to+the+company+in+control+of+the+integration+ID.```

Along with mismatching hash. How hard is that.

I had to dig into your node_modules c'mon

Dear future me. Use the same email as the one on you account.
Hope you finally landed on your billion dollar idea ;)

**Comment by TafadzwaD** [comment]
> @TafadzwaD Are you familiar with the SDK's codebase? Or we can have a quick call and I can show you what needs to be updated. Then you can submit a PR to the repo when done. That would save me from having to implement the solution myself

Let us have a quick call then you can show me what need to be updated @iammerus . I am familiar with the codebase

**Comment by thinkDigitalZw** [comment]
Omg, unbelievable.

Yes, [PayNow](https://www.paynow.co.zw) has not done something about the error handling,
but on the [docs](https://developers.paynow.co.zw/docs/test_mode.html) there is a clearly written point to note.

**N.B. The authemail field supplied during test mode should match one of the login email addresses for the merchant account being tested.**

This means if the account you used to obtain integration keys is `test@dev.io`, when passing the email on the `post`
request, `test@dev.io` should be used when testing.

So I suggest a thorough reading of the docs before implementation to any developer in the future.
This is to avoid the frustration and time wasting digging into a `bug`, that can be avoided if we read the docs.

Till the issue is fixed, I'm out. ✌🏽
